test_that("smatplot works", {
  expect_no_condition(smatplot(ppm,avo3))
  expect_no_condition(smatplot(ppm,avo3[1,]))
  expect_no_condition(smatplot(ppm,avo3,roi=c(1.4,1.6)))
  expect_no_condition(smatplot(ppm,avo3,roi=c(1.4,1.6),ylim=c(0,5e5)))
  expect_no_condition(smatplot(ppm,avo3,by=2,col=factor(c("a","a","b")),legend="topleft"))
  expect_no_condition(smatplot(ppm,avo3,resolution="full"))
  expect_no_condition(smatplot(ppm,avo3,resolution="full",reduce=max))
  expect_no_condition(smatplot(ppm,avo3,stacked=TRUE))
  expect_no_condition(smatplot(ppm,avo3,stacked=TRUE,by=2,legend="topleft"))
  expect_no_condition(smatplot(ppm,avo3,stacked=TRUE,ylim=c(0,2e6)))
})